### ISSUE TITLE
SE VOLESSI FARE UNA CHAT SOLO VERSO UN CONTATTO?

### ISSUE THREAD

**Issue by schulz89sp** [iFede94/WhatsChat#1]
Ciao Fede, grazie per il tutorial.
Io avrei però bisogno di fare una chat verso una sola singola persona...
Mi spiego, l'utente entra e chatta solo con lo sviluppatore.
Come faccio?

**Comment by iFede94** [comment]
puoi fare che al posto di avere il + per creare una nuova chat, quando l'utente apre l'app viene creata in automatico una chat verso quella persona.

**Comment by schulz89sp** [comment]
Ok, fatto grazie!
Implementerai mai le notifiche se arriva un messaggio e l'app non è aperta?

**Comment by iFede94** [comment]
Sì, appena ho tempo continuo anche con queste funzioni che sono abbastanza utili.
